-- Generated by the Organizer Library (Wed Mar  5 22:23:10 2025)
return {
    [1]={
        ["log_name"]="floral gauntlets", 
        ["id"]=27137, 
        ["name"]="floral gauntlets", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="aptitude mantle +1", 
        ["id"]=27604, 
        ["name"]="aptitude mantle +1", 
        ["count"]=1
    }
}