-- Generated by the Organizer Library (Wed Mar  5 22:23:10 2025)
return {
    [1]={
        ["log_name"]="samnuha tights", 
        ["id"]=27295, 
        ["name"]="samnuha tights", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="adhemar jacket +1", 
        ["id"]=25687, 
        ["name"]="adhemar jacket +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="reiki yotai", 
        ["id"]=26321, 
        ["name"]="reiki yotai", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="pixie hairpin +1", 
        ["id"]=26696, 
        ["name"]="pixie hairpin +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="luzaf's ring", 
        ["id"]=15810, 
        ["name"]="luzaf's ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="chasseur's gants +2", 
        ["id"]=23235, 
        ["name"]="chasseur's gants +2", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="meghanada cuirie +2", 
        ["id"]=25791, 
        ["name"]="meg. cuirie +2", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="sanctity necklace", 
        ["id"]=26023, 
        ["name"]="sanctity necklace", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="kishar ring", 
        ["id"]=26188, 
        ["name"]="kishar ring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="blurred knife +1", 
        ["id"]=20602, 
        ["name"]="blurred knife +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="lanun tricorne +3", 
        ["id"]=23414, 
        ["name"]="lanun tricorne +3", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="lanun bottes +3", 
        ["id"]=23682, 
        ["name"]="lanun bottes +3", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="ishvara earring", 
        ["id"]=27537, 
        ["name"]="ishvara earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="adhemar wristbands +1", 
        ["id"]=27118, 
        ["name"]="adhemar wrist. +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="anarchy +2", 
        ["id"]=19611, 
        ["name"]="anarchy +2", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="camulus's mantle", 
        ["count"]=1, 
        ["id"]=26262, 
        ["name"]="camulus's mantle", 
        ["augments"]={
            [1]="STR+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="STR+10", 
            [4]="Weapon skill damage +10%", 
            [5]="Mag. Evasion+15"
        }
    }, 
    [18]={
        ["log_name"]="eabani earring", 
        ["id"]=27540, 
        ["name"]="eabani earring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="carmine cuisses +1", 
        ["id"]=27207, 
        ["name"]="carmine cuisses +1", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="meghanada gloves +2", 
        ["id"]=25829, 
        ["name"]="meg. gloves +2", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="nusku shield", 
        ["id"]=26421, 
        ["name"]="nusku shield", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="epaminondas's ring", 
        ["id"]=26214, 
        ["name"]="epaminondas's ring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="barataria ring", 
        ["id"]=28548, 
        ["name"]="barataria ring", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="regal necklace", 
        ["id"]=26038, 
        ["name"]="regal necklace", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="dingir ring", 
        ["id"]=26187, 
        ["name"]="dingir ring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="samnuha coat", 
        ["id"]=26973, 
        ["name"]="samnuha coat", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="rostam", 
        ["id"]=21581, 
        ["name"]="rostam", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="meghanada chausses +2", 
        ["id"]=25880, 
        ["name"]="meg. chausses +2", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="sroda ring", 
        ["id"]=26221, 
        ["name"]="sroda ring", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="laksamana's frac +3", 
        ["id"]=23458, 
        ["name"]="laksa. frac +3", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="mache earring +1", 
        ["id"]=26081, 
        ["name"]="mache earring +1", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="compensator", 
        ["id"]=21482, 
        ["name"]="compensator", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="arciela's grace +1", 
        ["id"]=28369, 
        ["name"]="arciela's grace +1", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="naegling", 
        ["id"]=21621, 
        ["name"]="naegling", 
        ["count"]=1
    }
}