-- Generated by the Organizer Library (Wed Mar  5 22:23:10 2025)
return {
    [1]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Attack+10", 
            [2]="\"Waltz\" potency +10%", 
            [3]="AGI+4", 
            [4]="Accuracy+9"
        }
    }, 
    [2]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Accuracy+19 Attack+19", 
            [2]="\"Triple Atk.\"+4", 
            [3]="DEX+5", 
            [4]="Accuracy+8", 
            [5]="Attack+11"
        }
    }, 
    [3]={
        ["log_name"]="nyame helm", 
        ["count"]=1, 
        ["id"]=23761, 
        ["name"]="nyame helm", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [4]={
        ["log_name"]="nyame sollerets", 
        ["id"]=23789, 
        ["name"]="nyame sollerets", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="doomsday", 
        ["id"]=21476, 
        ["name"]="doomsday", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="nyame flanchard", 
        ["count"]=1, 
        ["id"]=23782, 
        ["name"]="nyame flanchard", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [7]={
        ["log_name"]="camulus's mantle", 
        ["count"]=1, 
        ["id"]=26262, 
        ["name"]="camulus's mantle", 
        ["augments"]={
            [1]="\"Snapshot\"+10"
        }
    }, 
    [8]={
        ["log_name"]="camulus's mantle", 
        ["count"]=1, 
        ["id"]=26262, 
        ["name"]="camulus's mantle", 
        ["augments"]={
            [1]="AGI+20", 
            [2]="Rng.Acc.+20 Rng.Atk.+20", 
            [3]="Rng.Acc.+10", 
            [4]="\"Store TP\"+10"
        }
    }, 
    [9]={
        ["log_name"]="camulus's mantle", 
        ["count"]=1, 
        ["id"]=26262, 
        ["name"]="camulus's mantle", 
        ["augments"]={
            [1]="AGI+20", 
            [2]="Rng.Acc.+20 Rng.Atk.+20", 
            [3]="AGI+10", 
            [4]="Weapon skill damage +10%"
        }
    }, 
    [10]={
        ["log_name"]="camulus's mantle", 
        ["count"]=1, 
        ["id"]=26262, 
        ["name"]="camulus's mantle", 
        ["augments"]={
            [1]="AGI+20", 
            [2]="Mag. Acc+20 /Mag. Dmg.+20", 
            [3]="AGI+10", 
            [4]="Weapon skill damage +10%"
        }
    }, 
    [11]={
        ["log_name"]="camulus's mantle", 
        ["count"]=1, 
        ["id"]=26262, 
        ["name"]="camulus's mantle", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Accuracy+10", 
            [4]="\"Store TP\"+10"
        }
    }, 
    [12]={
        ["log_name"]="nyame mail", 
        ["id"]=23768, 
        ["name"]="nyame mail", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="gleti's knife", 
        ["id"]=21567, 
        ["name"]="gleti's knife", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="eminent bullet", 
        ["id"]=21331, 
        ["name"]="eminent bullet", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="commodore charm +2", 
        ["id"]=25515, 
        ["name"]="comm. charm +2", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="herculean helm", 
        ["count"]=1, 
        ["id"]=25642, 
        ["name"]="herculean helm", 
        ["augments"]={
            [1]="Mag. Acc.+16 \"Mag.Atk.Bns.\"+16", 
            [2]="Enmity-3", 
            [3]="INT+9", 
            [4]="\"Mag.Atk.Bns.\"+13"
        }
    }, 
    [17]={
        ["log_name"]="nyame gauntlets", 
        ["id"]=23775, 
        ["name"]="nyame gauntlets", 
        ["count"]=1
    }
}